# Generated by Django 3.2.13 on 2024-05-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
