openapi: 3.0.0
info:
  title: Cash Collection API
  description: RESTful API endpoints for Cash Collection application
  version: 1.0.0

paths:
  /api/{userId}/tasks:
    get:
      summary: List Completed Tasks
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: A list of completed tasks

  /api/{userId}/next_task:
    get:
      summary: Get Next Task
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: The next task for the CashCollector

  /api/{userId}/status:
    get:
      summary: Check Collector Status
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: Returns true if the CashCollector is frozen

  /api/{userId}/collect:
    post:
      summary: Collect Cash
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  description: Amount of cash collected
                task_id:
                  type: integer
                  description: ID of the task for which cash is collected
                manager_id:
                  type: integer
                  description: ID of the Manager
      responses:
        '201':
          description: Cash collected successfully

  /api/{userId}/pay:
    post:
      summary: Pay Cash to Manager
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  description: Amount of cash to pay to the Manager
                manager_id:
                  type: integer
                  description: ID of the Manager
      responses:
        '201':
          description: Cash paid to Manager successfully
